inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  NewCops: enable

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes


# Add the frozen_string_literal comment to the top of files
# to help transition to frozen string literals by default.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# No trailing space differentiates better from the block:
# foo} means hash, foo } means block.
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

RSpec/FilePath:
  Enabled: false
